version: "3.8"
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: wallet123
      POSTGRES_DB: db_my_wallet
    ports:
      - "5433:5432"
    volumes:
      - ./db-init-scripts:/docker-entrypoint-initdb.d
      - /postgres-data:/var/lib/postgresql/data